### ISSUE TITLE
Adresse des BME280 in der BME280I2C.h ändern

### ISSUE THREAD

**Issue by chkbln** [TomMajor/SmartHome#12]
Hallo TomMajor,
Beim den BME280 Modulen gibt es welche die die Adresse I2CAddr_0x76 oder I2CAddr_0x77 nutzen.
Ist es richtig, dass die entsprechend vom Modul genutzte Adresse in der Datei BME280I2C.h angepasst werden muss? 
Das wäre dann der Eintrag **I2CAddr _addr   = I2CAddr_0x_76_ oder _77_**.
Vielleicht kannst du das in der Dokumentation mit angeben.

Viele Grüße Christof

**Comment by TomMajor** [comment]
Ja, beim BME280 ist die I2C Addr noch nicht über den sketch konf.
Die steht in BME280I2C.h, ja. Ich schaue noch mal demnächst ob ich die auch vom sketch konf. machen kann.
