### ISSUE TITLE
Leiterplatte wo kaufen?

### ISSUE THREAD

**Issue by Fiiti** [TomMajor/SmartHome#20]
Hi,
Sei doch bitte so nett und zeige den Link, Hersteller, Forum, Shop, etc. pp. wo man die Leiterplatte kaufen kann.
Ich habe empfunden auf alle Links geklickt, habe aber immer nur mich im Kreis gedreht.

Das Gehäuse habe ich dann irgendwann gefunden, da Du irgendwo den Namen verwendet hast.

VIelleicht magst Du diese ja auch in der Übersicht etwas deutlicher aufzeigen? 
Ich habe diese Seite durch das Suchen nach MAX44009 gefunden und bin sehr begeistert. Somit fehlt mir aber sämtlicher Background zum Urposting oder ähnlichem.

Danke Dir im Voraus.
Fi

**Comment by TomMajor** [comment]
Welche Leiterplatte, die vom HB-UNI-Sensor1 ? Die Gerberdaten dafür liegen im PCB Ordner, damit kann man bei Platinenherstellern bestellen.
Der Originalthread zum Sensor:
[Selbstbau HM_WDS10_TH_O mit Luftdruckmessung](https://forum.fhem.de/index.php/topic,20620.0.html)
