### ISSUE TITLE
Nur 2 Messwerte Anzeigen

### ISSUE THREAD

**Issue by chkbln** [TomMajor/SmartHome#22]
Hallo Tom

Was muss ich konfigurieren, damit ich nur die Werte der angeschlossen Sensoren angezeigt bekomme.
Ich habe nur den MAX 44009 angeschlossen. Somit brauche ich nur 2 Messwerte.
![grafik](https://user-images.githubusercontent.com/11814828/59963146-7c004d80-94ef-11e9-936e-df51c762e6f3.png)

Viele Grüße Christof

**Comment by TomMajor** [comment]
Du müsstest das xml an dieser Stelle editieren
[https://github.com/TomMajor/SmartHome/blob/master/HB-UNI-Sensor1/CCU_RM/src/addon/firmware/rftypes/hb-uni-sensor1.xml#L143](url)
und die nicht benötigten Werte/Zeile einfach löschen.

Danach musst du m.E. den Sensor in der CCU löschen und neu anlernen, um den neuen Stand zu bekommen.

Das alles geht solange **alle** HB-UNI-Sensor1 genau diese Sensorkonf. haben sollen. Bei Mischbetrieb wird es komplizierter, dann müsstest du über die Firmware Version verschiedene xml und Geräte verwalten.
