### ISSUE TITLE
Erweiterung um Temperatur und Feuchtesensor SHT21 / Si7021

### ISSUE THREAD

**Issue by chianti2000** [TomMajor/SmartHome#23]
Ist es dir  möglich,  den Temperatur- und Feuchtesensor SHT21 / Si7021 in den UNI-SENSOR einzubinden.
Er soll eine geringe Fehlertoleranz bei Feuchte aufweisen, wo der BME 280 ja etwas problematisch erscheint. Könnte dann mit dem BMP 280 im Unisensor arbeiten und den BME 280 ersetzen. 

Viele Grüße Gerd

**Comment by TomMajor** [comment]
Prinzipiell ja, hätte sogar einen unbenutzten SHT21 rumliegen.
Momentan nur ein Zeitproblem, weiß nicht wie dringend es wäre.

**Comment by chianti2000** [comment]
Kein Problem hat noch Zeit, wäre aber gut, wenn es nicht in Vergessenheit gerät. Laut Jerome  gibt es in der AskSinPP den Sensor schon. 
https://github.com/pa-pa/AskSinPP/blob/master/sensors/Si7021.h
https://github.com/jp112sdl/Beispiel_AskSinPP/tree/master/examples/HM-WDS40-TH-I-SI7021
Würde ihn aber gerne im UNI-Sensor und nicht Stand -Alone nutzen wollen.

**Comment by TomMajor** [comment]
ich schaue ob ich den SHT21 in den nächsten Wochen eingebaut bekomme und lasse den thread mal so lange offen.

**Comment by chianti2000** [comment]
Danke

**Comment by TomMajor** [comment]
Support für SHT21 / Si7021 hinzugefügt.

**Comment by chianti2000** [comment]
DANKE! 👍
