### ISSUE TITLE
AS3935 Sensor

### ISSUE THREAD

**Issue by Michel83** [TomMajor/SmartHome#25]
Hi, ist es möglich ein AS3935 Blitzsensor mit aufzunehmen? 

Gruss und super Arbeit

**Comment by TomMajor** [comment]
Habe mich noch nicht mit diesem beschäftigt, prinzipiell wahrscheinlich schon. Stromverbrauch ist ev. ein Thema da der Sensor wohl immer an sein muss?

**Comment by TomMajor** [comment]
Stromverbrauch ist ca. 70uA, das müsste für mehrere Jahre reichen. Man könnte also wahrscheinlich einen Blitzdetektor mit dem Unisensor bauen.
Falls mir jemand einen Sensor sponsert schaue ich mir das im Winter mal an..

**Comment by Michel83** [comment]
Hi, danke für die Antwort.

Ich würde ein Sponsoren :-)

**Comment by TomMajor** [comment]
ok, wenn es ok für dich ist dass es ein paar Wochen dauern kann bis ich damit anfange (irgendwann im Nov.) können wir das gerne machen.
Weiteres am besten über PN im HM oder FHEM Forum.

**Comment by Michel83** [comment]
PM im HM Forum geschrieben

Grüße

**Comment by TomMajor** [comment]
Sensor bekommen, vielen Dank, Thema ist in Arbeit.
