### ISSUE TITLE
HB-Sen-Jet

### ISSUE THREAD

**Issue by audi2010** [TomMajor/SmartHome#26]
Hallo Tom,
hat jemand für den HB-Sen-Jet Platinen bestellt und könnte eine abgeben?

Übrigens: Tolle Arbeit, die du da machst. Danke dafür

Gruss Rainer

**Comment by TomMajor** [comment]
Danke für die Blumen.
Ich könnte eine abgeben, schreib mir am besten eine PN im HM Forum.
