### ISSUE TITLE
404 pcb files

### ISSUE THREAD

**Issue by schuballaa** [TomMajor/SmartHome#31]
Hallo, wollte gerade zum ätzen runterladen, aber ich bekomme den fehler 404.

Lg Daniel

**Comment by jp112sdl** [comment]
Hi,

aus deiner Anfrage geht leider nicht hervor, welche der Platinen du herunterladen wolltest.

Vermutlich die `tmStamp`? Aber die gibts auch noch gar nicht zum Download. Dort steht noch "WIP" -> "Work in progress"

**Comment by schuballaa** [comment]
Achso, schade, ja, gebau die meinte ich, dann übe ich mich. In Geduld 😊👍
Lg Daniel 

Am 29. Dezember 2019 22:01:19 MEZ schrieb "Jérôme" <notifications@github.com>:
>Hi,
>
>aus deiner Anfrage geht leider nicht hervor, welche der Platinen du
>herunterladen wolltest.
>
>Vermutlich die `tmStamp`? Aber die gibts auch noch gar nicht zum
>Download. Dort steht noch "WIP" -> "Work in progress"
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/TomMajor/SmartHome/issues/31#issuecomment-569541675

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by TomMajor** [comment]
Lade ich heute nachmittag oder Abend hoch.

**Comment by TomMajor** [comment]
ich habe die Stückliste und die Gerberdateien hochgeladen.
