### ISSUE TITLE
Standardwerte für transmitDevTryMax, updIntervall, altitude usw.

### ISSUE THREAD

**Issue by HMelzer** [TomMajor/SmartHome#39]
Hi Tom,

ich mühe mich schon seit geraumer Zeit erfolglos ab, zu ergründen, woher die Werte für die o.g. Daten kommen, die im Seriellen Monitor angezeigt werden:
![Monitor](https://user-images.githubusercontent.com/49859355/83756080-cd590c80-a66e-11ea-9bb0-4305bcf64c83.jpg)

Die Standardwerte, die ich im Sketch eingetragen habe, können es nicht sein:
![Sketch](https://user-images.githubusercontent.com/49859355/83756173-f7123380-a66e-11ea-9986-343f855c13fc.jpg)

Es können auch keine Werte sein, die aus der Homematik selbst kommen, da der Sensor noch nicht daran angemeldet ist.
Woher also bezieht das kompilierte Programm seine Werte bzw. wo wären diese ggf. zu ändern?

**Comment by jp112sdl** [comment]
> Da hilft ein longpress des Config buttons, das macht ein komplettes device reset (lässt sich im seriellen Monitor beobachten)

... und dann werden die Werte mit denen in defaults() belegt.

**Comment by HMelzer** [comment]
Genau das war es wohl!
Hat funktioniert, währe ich aber nie darauf gekommen.
Vielen Dank und ein schönes Wochenende.
