### ISSUE TITLE
Version ist falsch

### ISSUE THREAD

**Issue by MathiasJZ** [TomMajor/SmartHome#42]
habe gerade versucht, das hb-tm-devices-addon upzudaten.
nach dem Update bekomme ich immer noch die Meldung, es gäbe ein neues 2.5.1 und das ältere 2.5.0 wäre installiert.
Gruß,
Mathias

**Comment by TomMajor** [comment]
Danke für den Hinweis. Habe gerade die Version auf 2.50 rückgesetzt.
Es wird eine neue Version geben, aber noch nicht alle Änderungen gemacht bzw. getestet,
Setzen der neuen Version war def. zu früh.

**Comment by MathiasJZ** [comment]
Ich kann jetzt aber ich nenne sie mal 2.5.0a lassen, oder soll ich die 
originale 2.5.0 installieren?
Gruß,
Mathias

**Comment by TomMajor** [comment]
Kannst alles so lassen wie es ist.
Es wurde nur die Textdatei mit der Version "zu früh" geändert, siehe commits.
Das eigentliche AddOn **hb-tm-devices-addon.tgz** wurde noch gar nicht angefasst.

**Comment by TomMajor** [comment]
Seit gestern ist die neue Version draußen.

**Comment by MathiasJZ** [comment]
Gestern wurde sie auch installiert
Gruß, 
Mathias
