### ISSUE TITLE
Altitude wird bei Druckermittlung mit BME280 nicht berücksichtigt

### ISSUE THREAD

**Issue by GerdS1960** [TomMajor/SmartHome#44]
Im Sketch HB-UNI-Sensor-1 wird beim Aufruf der BME280-measure-Funktion ein Wert altitude übergeben, der immer 0 ist, was zu einer falsch kalkulierten Luftdruckangabe führt.

**Comment by TomMajor** [comment]
die Höhe wird über das WebUI in den Seinstellungen für das Gerät gesetzt
https://github.com/TomMajor/SmartHome/tree/master/HB-UNI-Sensor1#raspberrymatic-webui
Danach den Config Button drücken.

**Comment by GerdS1960** [comment]
Wer lesen kann ist klar im Vorteil. Danke für den Hinweis.

Von meinem iPad gesendet
